import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Script from "next/script";
import Footer from "./components/footer";
import Header from "./components/header";
import { NewsProvider } from "./context/NewsContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <head>
        <Script
          src="https://platform.twitter.com/widgets.js"
          strategy="lazyOnload"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <NewsProvider>
      <Header />
        <main>
          {children}
          <Script
          src="https://platform.twitter.com/widgets.js"
          strategy="lazyOnload"
        />
        </main>
        <Footer />
        </NewsProvider>
      </body>
    </html>
  );
}
